use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'     #官方仓库地址
source 'ssh://KQGitlab/gerrit/KQB_Spec_iOS'    #私有仓库地址

platform :ios, '9.0'

target 'KQPayment_Example' do
  pod 'KQPayment', :path => '../'

  target 'KQPayment_Tests' do
    inherit! :search_paths

    
  end
end
